#!/bin/bash

CUDA_VISIBLE_DEVICES=1 python theory_TAPS_approximation.py \
       --dataset mnist --fast-reg --use-vanilla-ibp \
       --net cnn_3layer_tiny --load-model ./test_models/theory_approximation/mnist/eps0.05/small_box_trained/cnn_3layer_tiny/init_fast/alpha5.0/fast_reg/model.ckpt \
       --cert-weight 1 \
       --lr 0.0005 --L2-reg 0 --lr-milestones 50 60 \
       --train-eps 0.1 --test-eps 0.05  --train-steps 20 --test-steps 20  \
       --train-batch 256 --test-batch 5 \
       --pgd-weight-start 1 --pgd-weight-end 1 \
       --grad-clip 10 \
       --n-epochs 70 --start-epoch-eps 0 --end-epoch-eps 20 \
       --min-eps-pgd 0 \
       --soft-thre 0.5 \
       --alpha-box 5  \
       --save-dir ./test_models/theory_approximation/mnist/eps0.05/SABR_results
