#!/bin/bash

seed=123

# eps = 0.1

### TAPS train

# CUDA_VISIBLE_DEVICES=0 python mix_train.py \
#        --dataset mnist --init fast --fast-reg --random-seed $seed \
#        --net cnn_7layer_bn \
#        --cert-weight 1 \
#        --lr 0.0005 --L2-reg 0 --lr-milestones 50 60 \
#        --train-eps 0.2 --test-eps 0.1  --train-steps 20 --test-steps 20  \
#        --train-batch 256 --test-batch 256  \
#        --pgd-weight-start 1 --pgd-weight-end 1 \
#        --grad-clip 10 \
#        --n-epochs 70 --start-epoch-eps 0 --end-epoch-eps 20 \
#        --min-eps-pgd 0 \
#        --soft-thre 0.5 \
#        --alpha-box 5  \
#        --save-dir ./models/seed_$seed \
#        --block-sizes 17 4

### STAPS train

# CUDA_VISIBLE_DEVICES=0 python mix_train.py \
#        --dataset mnist --fast-reg  \
#        --use-small-box --eps-shrinkage 0.4 --L1-reg 2e-5 --random-seed $seed \
#        --net cnn_7layer_bn \
#        --cert-weight 1 \
#        --lr 0.0005 --L2-reg 0 --lr-milestones 50 60 \
#        --train-eps 0.2 --test-eps 0.1  --train-steps 20 --test-steps 20  \
#        --train-batch 256 --test-batch 256  \
#        --pgd-weight-start 1 --pgd-weight-end 1 \
#        --grad-clip 10 \
#        --n-epochs 70 --start-epoch-eps 0 --end-epoch-eps 20 \
#        --min-eps-pgd 0 \
#        --soft-thre 0.5 \
#        --alpha-box 5  \
#        --save-dir ./models/seed_$seed \
#        --block-sizes 17 4


# eps = 0.3

### TAPS train

# CUDA_VISIBLE_DEVICES=0 python mix_train.py \
#        --dataset mnist --init fast --fast-reg --random-seed $seed \
#        --net cnn_7layer_bn \
#        --cert-weight 1 \
#        --lr 0.0005 --L2-reg 0 --lr-milestones 50 60 \
#        --train-eps 0.4 --test-eps 0.3  --train-steps 20 --test-steps 20  \
#        --train-batch 256 --test-batch 256  \
#        --pgd-weight-start 1 --pgd-weight-end 1 \
#        --grad-clip 10 \
#        --n-epochs 70 --start-epoch-eps 0 --end-epoch-eps 20 \
#        --min-eps-pgd 0 \
#        --soft-thre 0.5 \
#        --alpha-box 5  \
#        --save-dir ./models/seed_$seed \
#        --block-sizes 17 4


### STAPS train


# CUDA_VISIBLE_DEVICES=0 python mix_train.py \
#        --dataset mnist --init fast --fast-reg --use-small-box --eps-shrinkage 0.6 --random-seed $seed \
#        --net cnn_7layer_bn \
#        --cert-weight 1 \
#        --lr 0.0005 --L2-reg 0 --lr-milestones 50 60 \
#        --train-eps 0.4 --test-eps 0.3  --train-steps 20 --test-steps 20  \
#        --train-batch 256 --test-batch 256  \
#        --pgd-weight-start 1 --pgd-weight-end 1 \
#        --grad-clip 10 \
#        --n-epochs 70 --start-epoch-eps 0 --end-epoch-eps 20 \
#        --min-eps-pgd 0 \
#        --soft-thre 0.5 \
#        --alpha-box 5  \
#        --L1-reg 2e-6 \
#        --save-dir ./models/seed_$seed \
#        --block-sizes 17 4